#!/bin/sh
#
# Fixes the permissions to allow members of the 'backlight-users' group to
# update the brightness of the screen or keyboard on the laptop (ASUS Zenbook
# UX31A).
#
# Only need to run this once after a fresh install.

for path in /sys/class/backlight/intel_backlight /sys/class/leds/asus\:\:kbd_backlight; do
  file=$path/brightness
  chmod 664 $file;
  chgrp backlight-users $file;
done
